// הרשימה ההתחלתית. נטענת למסד הנתונים פעם אחת בלבד, בפעם הראשונה שמישהו פותח את הדף.
// אחרי זה משנים את הרשימה מתוך הדף עצמו (עריכת הרשימה).
export const DEFAULT_ITEMS = [
  {"id":"meat-1","cat":"meat","order":1,"name":"אנטריקוט","note":"4 סטייקים, כ-1 ק״ג"},
  {"id":"meat-2","cat":"meat","order":2,"name":"פרגיות","note":"כ-1 ק״ג"},
  {"id":"meat-3","cat":"meat","order":3,"name":"קבבים או המבורגרים","note":"8 יח׳"},
  {"id":"meat-4","cat":"meat","order":4,"name":"כנפיים או לבבות עוף","note":"תוספת, כ-½ ק״ג"},
  {"id":"meat-5","cat":"meat","order":5,"name":"נקניקיות","note":"חבילה, לבוקר או ללילה"},
  {"id":"grill-1","cat":"grill","order":1,"name":"מנגל","note":"גדול מספיק ל-4"},
  {"id":"grill-2","cat":"grill","order":2,"name":"פחמים","note":"שק של 5 ק״ג לפחות"},
  {"id":"grill-3","cat":"grill","order":3,"name":"קוביות הצתה ומצית","note":"עדיף מצית ארוך"},
  {"id":"grill-4","cat":"grill","order":4,"name":"נפנף","note":"או פן, יש גנרטור"},
  {"id":"grill-5","cat":"grill","order":5,"name":"רשתות ושיפודים","note":"רשת רגילה + רשת כפולה"},
  {"id":"grill-6","cat":"grill","order":6,"name":"מלקחיים וכפפת חום","note":"+ מברשת לניקוי הרשת"},
  {"id":"kitchen-1","cat":"kitchen","order":1,"name":"צידנית לבשר","note":"+ קרחונים מוקפאים"},
  {"id":"kitchen-2","cat":"kitchen","order":2,"name":"צידנית לשתייה","note":"גדולה, לבירות ולמים"},
  {"id":"kitchen-3","cat":"kitchen","order":3,"name":"פק״ל קפה","note":"גזייה, מיכל גז ופינג׳אן"},
  {"id":"kitchen-4","cat":"kitchen","order":4,"name":"מחבת גדולה","note":"לשקשוקה בבוקר"},
  {"id":"kitchen-5","cat":"kitchen","order":5,"name":"קרש חיתוך וסכין","note":"סכין חדה לבשר ולסלט"},
  {"id":"kitchen-6","cat":"kitchen","order":6,"name":"פותחן וחולץ פקקים","note":"תמיד נשכח"},
  {"id":"sides-1","cat":"sides","order":1,"name":"פיתות או לחמניות","note":"כ-16, לערב ולבוקר"},
  {"id":"sides-2","cat":"sides","order":2,"name":"סלטים מוכנים","note":"חומוס, טחינה, מטבוחה, חצילים"},
  {"id":"sides-3","cat":"sides","order":3,"name":"ירקות לסלט","note":"עגבניות, מלפפונים, בצל, לימון"},
  {"id":"sides-4","cat":"sides","order":4,"name":"תפוחי אדמה ובצלים","note":"לגחלים, בנייר כסף"},
  {"id":"sides-5","cat":"sides","order":5,"name":"חמוצים וחריף","note":"מלפפון חמוץ, סחוג, עמבה"},
  {"id":"sides-6","cat":"sides","order":6,"name":"תבלינים ושמן זית","note":"מלח גס, פלפל שחור, פפריקה"},
  {"id":"drinks-1","cat":"drinks","order":1,"name":"מים","note":"2 שישיות, 18 ליטר"},
  {"id":"drinks-2","cat":"drinks","order":2,"name":"בירה","note":"24 בקבוקים"},
  {"id":"drinks-3","cat":"drinks","order":3,"name":"שתייה קלה","note":"קולה, סודה"},
  {"id":"drinks-4","cat":"drinks","order":4,"name":"ערק או וויסקי","note":"בקבוק אחד"},
  {"id":"drinks-5","cat":"drinks","order":5,"name":"קרח","note":"2 שקיות, לקנות בדרך"},
  {"id":"morning-1","cat":"morning","order":1,"name":"קפה וסוכר","note":"קפה שחור לפינג׳אן"},
  {"id":"morning-2","cat":"morning","order":2,"name":"חלב","note":"קרטון, בצידנית"},
  {"id":"morning-3","cat":"morning","order":3,"name":"ביצים ורסק עגבניות","note":"12 ביצים, לשקשוקה"},
  {"id":"morning-4","cat":"morning","order":4,"name":"משהו מתוק לקפה","note":"עוגיות, ופלים, רוגלך"},
  {"id":"morning-5","cat":"morning","order":5,"name":"גרעינים וחטיפים","note":"גרעינים, בוטנים, ביסלי"},
  {"id":"morning-6","cat":"morning","order":6,"name":"פירות","note":"מה שיש בעונה"},
  {"id":"disposable-1","cat":"disposable","order":1,"name":"צלחות, כוסות וסכו״ם","note":"חד״פ, חבילה מכל סוג"},
  {"id":"disposable-2","cat":"disposable","order":2,"name":"נייר סופג ומפיות","note":"2 גלילים"},
  {"id":"disposable-3","cat":"disposable","order":3,"name":"נייר כסף ומגשי אלומיניום","note":"לתפוחי האדמה ולהגשת הבשר"},
  {"id":"disposable-4","cat":"disposable","order":4,"name":"שקיות זבל גדולות","note":"את כל הזבל לוקחים איתנו"},
  {"id":"disposable-5","cat":"disposable","order":5,"name":"סבון כלים וספוג","note":"לרשת ולמחבת"},
  {"id":"disposable-6","cat":"disposable","order":6,"name":"מגבונים לחים","note":"חבילה גדולה"},
  {"id":"disposable-7","cat":"disposable","order":7,"name":"נייר טואלט","note":"2–3 גלילים"},
  {"id":"camp-1","cat":"camp","order":1,"name":"שולחנות מתקפלים","note":"שניים: אחד להכנה ואחד לאוכל"},
  {"id":"camp-2","cat":"camp","order":2,"name":"כיסאות מתקפלים","note":"ארבעה, או שכל אחד מביא את שלו"},
  {"id":"camp-3","cat":"camp","order":3,"name":"גזיבו או יריעת צל","note":"+ יתדות וחבלים"},
  {"id":"camp-4","cat":"camp","order":4,"name":"ג׳ריקן מים","note":"20 ליטר, לשטיפה ולכיבוי הגחלים"},
  {"id":"camp-5","cat":"camp","order":5,"name":"ערכת עזרה ראשונה","note":"+ משחה לכוויות"},
  {"id":"camp-6","cat":"camp","order":6,"name":"נגד יתושים","note":"ספירלות או נרות סיטרונלה"},
  {"id":"camp-7","cat":"camp","order":7,"name":"שש־בש וקלפים","note":"לערב"},
  {"id":"power-1","cat":"power","order":1,"name":"גנרטור","note":"לבדוק שעובד לפני היציאה"},
  {"id":"power-2","cat":"power","order":2,"name":"דלק לגנרטור","note":"ג׳ריקן מלא"},
  {"id":"power-3","cat":"power","order":3,"name":"כבל מאריך ומפצל","note":"לתאורה, לרמקול ולמטענים"},
  {"id":"power-4","cat":"power","order":4,"name":"תאורה למחנה","note":"פרוז׳קטור לד או שרשרת נורות"},
  {"id":"power-5","cat":"power","order":5,"name":"פנס נטען","note":"גיבוי לשעות שהגנרטור כבוי"},
  {"id":"power-6","cat":"power","order":6,"name":"רמקול בלוטות׳","note":"טעון"}
];

// "כל אחד לעצמו": הרשימה ההתחלתית של מה שכל אחד אורז לעצמו. גם היא נטענת למסד פעם אחת בלבד.
// המזהים זהים לאלה של הגרסה הקודמת, כדי שסימונים ששמורים כבר בטלפונים יישארו.
export const DEFAULT_PERSONAL = [
  { id: "me-tent", order: 1, name: "אוהל, יתדות ופטיש" },
  { id: "me-bag", order: 2, name: "שק שינה" },
  { id: "me-mat", order: 3, name: "מזרן או מזרון מתנפח (+ משאבה)" },
  { id: "me-pillow", order: 4, name: "כרית" },
  { id: "me-headlamp", order: 5, name: "פנס ראש" },
  { id: "me-warm", order: 6, name: "ביגוד חם ללילה" },
  { id: "me-towel", order: 7, name: "מגבת וכלי רחצה" },
  { id: "me-flipflops", order: 8, name: "כפכפים" },
  { id: "me-sun", order: 9, name: "כובע וקרם הגנה" },
  { id: "me-spray", order: 10, name: "ספריי נגד יתושים" },
  { id: "me-charger", order: 11, name: "מטען וכבל לטלפון" },
  { id: "me-meds", order: 12, name: "תרופות אישיות" }
];
